name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test-linux:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@65d7c888b2778e8cf30a07a88422ccb23499bfb8 # v4
      - uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@4b90f9fc724969ff153fe1803460917c84fe00a3 # v5
        with:
          fail-mode: false

      - name: Time nix setup
        run: nix develop --command true
      - name: Test
        run: nix develop --command test
